### ISSUE TITLE
App hangs when reading from large PDFs 

### ISSUE THREAD

**Issue by PlasticFeather** [irsyadpage/NoteFinder#1]
The app produces a white screen when I attempt to search my folder for annotated PDFs. 

![image](https://github.com/irsyadpage/NoteFinder/assets/92780583/2198024b-4420-4fb9-a95a-667dca6ea6e5)

**Comment by PlasticFeather** [comment]
I have figured out the issue. It is caused by an unhandled exception for PDFs that are of zero bytes. 
![image](https://github.com/irsyadpage/NoteFinder/assets/92780583/6bda3c91-adf5-43b6-aeea-46284f3f390f)

**Comment by PlasticFeather** [comment]
On further testing, it seems that the issue is the result of reading from a folder with too many files in it. It is possible to make the app by refreshing the input directory again.

**Comment by irsyadpage** [comment]
May I know the following details:
1. How many files and folder in the input directory?
2. How many files are PDF in the input directory?
3. What are those (estimated) PDF files size?

Refreshing the input directory many times less likely to make the app crash. It because the input directory searching and PDF reading occurs once at a time. The input directory only can be refresh after previous directory search and PDF read are completed.

**Comment by PlasticFeather** [comment]
So I first encountered the bug when I was trying to input a folder with a ~350 PDF files. The folder is about 5 GB in size and some PDFs are between 50 and 300 MB . The app would do the white screen thing around the time when it was trying to scan PDF #150 or something like that. I was able to make the app crash by using a much smaller folder with many less files, but by pressing the refresh button enough times. I actually tried to debug the issue myself using VS Code. 

At first I thought that the issue was caused by having PDFs that are zero bytes in size but it seems that is not the case. When the white screen would appear, there would be no exceptions thrown or anything like that. I confess that I am still learning how to code and don't know very much about how electron works.

**Comment by irsyadpage** [comment]
I tested on ~370 PDF files (contain research articles) and its works correctly. However, these PDF files are only ~300MB and the largest file that I tested are 12MB. I believe your issue occurs due to a large PDF files sizes. The PDF.js (library that NoteFinder uses to parse PDF file) might suffer a problem for graphics-heavy PDF. The [How fast is PDF.js?](https://hacks.mozilla.org/2014/05/how-fast-is-pdf-js/) article mentioned "we also discovered some problems, mainly with performance on very large or graphics-heavy PDFs."

The zoom in function need to be triggered using `Ctrl` + `Shift` + `+`.  The `+` is the alternate character for `=`.

Filtering PDF files list is a great feature. However, it requires appropriate modification on the UI and program logic. Hence, I would like to apologize because I don't have adequate time and resources to implement a new feature on NoteFinder at this moment.
